server:
  port: 18091
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8179
  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: web
    discovery-client-enabled: false
  sleuth:
    sampler:
      probability: 1
  redis:
    host: 172.16.116.100
  rabbitmq:
    host: 172.16.116.100
    virtual-host: /fengge
    username: fengge
    password: fengge
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 1
  thymeleaf:
    cache: false
feign:
  sentinel:
    enabled: true
thread:
  pool:
    coreSize: 100
    maxSize: 500
    keepalive: 60
    blockQueueSize: 1000
alipay:
  app_id: 2016101200666477
  gatewayUrl: https://openapi.alipaydev.com/gateway.do
  merchant_private_key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCSJC6ttv93vMImqRceUFwNWh3ZJgObO5m745ydYzE+z06WzWyPWB/rvI2k+bsZdctPrdbwxJPdtclzub827VGDzwBmqdBUoRirYoGWuNg5DddhDhenIHYTYNW8zWqWPgvE/w+d9rssU/dHh6RG74KvQRq9bReOBv7zEddyZbA/WMYXvbIaDFBtUgjqr1LeOdzhEj2o1AgTDtT/NqLqPqQKwkHAgNTT0pDMDfU5O4MeH0DMlJoaDscP8GLdhw14fZPxRIMtjtvs+ptKW74DrYfccweKIMDIHwJsYTMatydAqvxe/i6TnarPKl85nNc7/JMhtaRfTopebjurfbqVzs29AgMBAAECggEAH7ojOCuGguRD8ki7cCVaFrv9xurt1YG2+oeLtM+YHV68XRjz/JrRM0iYJ7zf1cMxBHdlNpg20edpeOpWjQIwtED4gVFUnUrsJCkaoTI4HwrWO4fnsqzldYeMX5TpEv0daQNGzLCIKjOAd9MG4y+UW5/ywjUw6/Cw4Ox6radOADJcP1nrvh1WrpA0cNWycgixvjBC2pcZ7MhkRPUyhfOMEiJVH00b96hqt1XeGk+HZbf0VfLi5nr958d40I3P7/Fq6SHPxzgVamMIc+wtsmvTxTQA13IJO6eILPYTuLVM7GmnIf37b2f+nPXJfxVCLaTwD0sdWgjqDSwxUYsxOqsEAQKBgQDo5PuhUHczq+WjdOk1UhqcpqhaXpwCfKytfTLvvU4s8I5pGrwhX6E4yAxWtIsKkFPREWL0hAnDcphE8SQV4KE5BFItT58tFFDZaSr/4SVZdQKUFFhx1jriCIGYbwFZjCWOCtrgeN1gU9gYN7L6TVR87n+TvqVoJfgg94qAPr+EwQKBgQCgo9tqY/C3fpUmUq+HkKv1LspPVrThv4JOa3YSHsu5SQMirRG5DcV9KDJ2I7ciKqFwxsuTtnHBR5os5JEFBSjz47irozXqP+7ewjtLFC6uoy3XXYxqn4r1MuSO0UKxY8uuv7bRyTfxJhnO32PUrOQm0jWfG+fkABFfVPCD3Fhb/QKBgQDkmgdo43vuK1gAZzyWix32EByGgAFw64Hv1UnPSylWMVYIUybBN4YgHzUFUrh8SQkM2Z0hWA3hXDWcznpWQyTdu6ESOuqKrDtj/LgpbI1lztYWFhZuvxMTVbgnsSZJCKjAUWVhGyJpcENYGixDRu6cptpxYpwnq8VwTqsTkQQawQKBgEF0guNG9b7PBVcoOf2zJV4yQp0xZ2LU9fOeNe4MPlaxOWXXv3D3+5CT4Hvi8awqUr3xQuJdZNysoFXKjIzPHXDDSWwmhMF+a4a4/hAJmTvvoa4voBeSCrz+j8Lh4ZsGXuhFlejFZNYOAFYbEEKIcC6hWNgMNuDgZjPCGH6iOh7BAoGBAJ1MpTAqxsxbXlvmqsoUd9y1WESWqm3g1njEXzHrq0K1hm1songTY1KrFxIF7kH7Mp3QldGF9jQ8gRuyDKXU8SS3Pv5ZRWuTL3zT/yt43Mbuo+0CmdYl3wv0z86IQMuJD1rcEsUe56Ka9XgluJb+OJbE7uG6rMDeQ6cj2hVqHl6u
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAm0CbzDSMv9508/xEgXOciNrNyvR6pdJVDQ7iuXpJNXcniJB94G+wB3jn8EDygAwsdYHiQH8B6kp7clQ0tY3EEVy7w8/gleOT5zSG5eqLjtHy7VdWsWiQbDH6Tsl5ZMrr92Ki0QbWxepL642BG/8EeKsi3+/wdSWPV0Ujbw1+lpTID5wpiQbpCYOOs5bAuhJeqJNa4ovVPm238CEzmXCYmpH4fnsh6pjO/BiSLrdMx8Z2xy+cjQ3wcEF0R8vGgOz+q9yiuVkXaPU6emLJ/m8baRlkREszl80AghKNgBuV0771jsRykA81oR+9iJo/tdpvqisGW4TLirnrq1iDLDHZOQIDAQAB
  notify_url: http://9glldacce2.52http.net/order/pay/success
